### ISSUE TITLE
Ship won't Launch. Doesnt recognize the fuel inside the spinal engine exhaust.

### ISSUE THREAD

**Issue by Reishe** [realthecaffiend/SOS2ExpSpinalEngines#17]
I really like the idea behind the mod, but I am having trouble launching the ship with the spinal engines alone. 

The SOS2 launch dialogue isn't counting the fuel inside the spinal engine exhaust.  I set up engines so there is no error message on the engine exhaust and I set up the chem fuel pipe network so that the engine exhaust is connected and filled. I went to the engine exhaust and set the desired fuel level to max. I went into dev mode to filled the engines to max just to be sure. 

When I add the normal sos2 engines the ship launches fine. 

Also as a feature request, could the entire spinal engine assembly act as a pipe network for chemfuel and uranium.  It feels weird to pipe fuel all the way to the exhaust when the the whole spinal assembly is supposed to increase power by manipulating the fuel. 

Again, thanks for the mod. It enables a lot of interesting ship designs.

**Comment by realthecaffiend** [comment]
Hey,

The lack of launch ended up as a design choice: engines below about 9 or 12 accelerators, depending on fuel type/ship size, provide less thrust per space occupied than just slapping on more regular engines. At a dozen accelerators, a ship launch at that scale is into the realm of encouraging people to make a mistake I keep doing myself: building way too big on the ground, haha. I also found the fuel it held was a bit small to enable launches at that scale anyhow and would mostly want additional, normal "boosters" strapped to the side. 

That said, you're entirely correct the description at least should mention this, I'll have to update that.

Also, that pipenet is a great idea for ease of build, and, as you point out, making sense. I'll need to tinker to make sure there is no unforseen impact but that should be easy to add for rimefeller and while I haven't looked at how the uranium fuelnet works (though I also use it), I assume? for it as well

**Comment by Reishe** [comment]
Hey man! Thanks for the quick response and update. I am playing with the changes now.

Those seem like fun problems to encounter and work through, though. I was really liking the idea of using the spinal engine as the only engine on my ship that I could gradually expand as the ship grew.  Could I make the spinal engines work with the SOS2 launch dialogue just by editing something in the XML? I know I can go in and increase the fuel capacity to whatever is needed for launch; which makes sense to me. In SOS2's implementation of "launch readiness" fuel capacity seems to be a proxy for thrust given larger engines hold more fuel and all engines of the same type provide the same thrust. Given that the spinal engines are more dynamic in their multipart construction, the ideal solution IMO would probably be to take the fuel capacity number and multiply that by the increased thrust from the accelerators to calculate the engine's "launch thrust".  But really I just wanna launch my silly spaceship with its one giant stupid engine and I am cool to just change the fuel capacity in the XML and pretend those calculations were happening xD.  

The uranium pipe net integration for the spinal components seems to work great. Thanks for implementing that! I guess to expand on the previous feature request, would it be possible to add compatibility with the fuel net from vanilla chemfuel expanded? Its the one I usually use. Also, I feel I would it make sense for the various spinal engine components to share the power net as well; I was pretty surprised to see that the spinal weapon components in SOS2 didn't share power. 

Thanks again. I hope this doesn't sound like a list of demands. I really appreciate all the work that you put into this.

**Comment by realthecaffiend** [comment]
Nah I don't see it as demands at all, I honestly only ever expected a couple dozen people to install this so I'm happy to see it get use and discussing better options!

Locally hacking it to allow launch is (probably!) super easy actually: If you look in SOS2 in 1.5/Defs/ThingDefs_Buildings/Buildings_Ship.xml, launchable engines just have "<takeOff>true</takeOff>" inside their CompProps_EngineTrail. Since I extended that class I'm about 95% sure if you just slap that in locally (inside my CompProperties_SpinalEngineTrail) it would allow it to launch, but make a backup save first etc etc haha. I like the "flavour" of it only working in microgravity and needing to strap on external temporary booster engines to get it out of a gravity well tbh, makes it feel like more of a big accomplishment, but I'm not going to stop anyone from tinkering with their own game for sure!

I forgot honestly that VE had the chemfuel expanded because I'm just used to rimmefeller, I'll look at that hopefully? this evening. The SOS2 pipenet mod I believe uses the same VE system and it was dead simple to add so assuming it's the same that's easy.
 I think I looked briefly at a powercomp on the support parts but had concerns about it being "heavy" and making them all constantly ticking parts eating TPS but I didn't really carefully investigate that, I'll have to check if my assumptions there were good or not

**Comment by Reishe** [comment]
That worked! I changed "takeoff" from "false" to "true" in the XML and I was able to launch the ship with only the spinal engine. 

Thanks for all the help and all the updates.  :)

**Comment by realthecaffiend** [comment]
Great to hear, I was... mostly, sure that would work hah. 

I also added power transmission and VE: Chemfuel piping to the support components tonight: It all seemed to work in my testing, but drop me a note if that's not the case

**Comment by Luzella** [comment]
This had me confused for quite a while, thought I was doing something wrong with the engine layout. Did you happen to have any luck with been able to loading uranium from the end cap of engine rather than the exhaust? Love the mod they really give off a cool startrek warp nacelle vibe.

**Comment by realthecaffiend** [comment]
The exhaust is the "smart" part so it holds the fuel currently: however, the accelerators, end parts, etc all support the "SOS2 fuel pipenet" mod  (or rimefeller/vanilla chemfuel expanded) so you can use those to load from the other end

I underestimated how many people would want to launch with them, so I have a local branch with some addon buildings to allow that, but I don't have any art for them yet! As such, release is still TBD @Luzella

**Comment by Luzella** [comment]
Ohhhh, I wasn't aware of the Pipenet for SOS2, that is pretty neat. I noticed Rimefella but didn't put 2 and 2 together. I'd been using the fueling dispensers from RimFactory, but the Pipenet does indeed make things easier for what I want to do. 

The main reason for me downloading the mod was in hope that it did a similar thing to the weight that it does to the thrust as a I was pretty much using my ship as a secondary base and before I knew it, 40k weight. XD

I will keep my eyes open for an artist and send them over here if I find one. Love the spinal engines and loking forward to see the addons once they are ready for release. [This ](https://cdn.discordapp.com/attachments/615358044775120908/1261159290518114394/20240712041601_1.jpg?ex=66929a5e&is=669148de&hm=ab7342e96917a61727b8c6fce22546d285e70d7b5c486fee690dadb99fcfcf9b&) is the hulk that they helped put into space. :) @realthecaffiend
